### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by tjelvar-olsson** [JIC-CSB/dtoolai#6]
To reproduce on Windows laptop without GPU.

Setup:

```
python3 -m venv env
.\env\Scripts\Activate.ps1
pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
pip install dtool-ai
git clone https://github.com/JIC-CSB/dtoolai.git
cd dtoolai
```

Command:

```
python scripts/apply_model_to_image.py http://bit.ly/2tbPzSB .\docs\source\non_mnist_three.png
```

Error message:

```
Traceback (most recent call last):
  File "scripts/apply_model_to_image.py", line 6, in <module>
    from torchvision.transforms.functional import to_tensor
  File "C:\Users\olssont\sandbox\dtoolai-testing\env\lib\site-packages\torchvision\__init__.py", line 3, in <module>
    from torchvision import models
  File "C:\Users\olssont\sandbox\dtoolai-testing\env\lib\site-packages\torchvision\models\__init__.py", line 1, in <module>
    from .alexnet import *
  File "C:\Users\olssont\sandbox\dtoolai-testing\env\lib\site-packages\torchvision\models\alexnet.py", line 1, in <module>
    import torch
  File "C:\Users\olssont\sandbox\dtoolai-testing\env\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
```

**Comment by tjelvar-olsson** [comment]
It may be that this is an issue with torch 1.5 on Windows: https://github.com/pytorch/pytorch/issues/37209
