### ISSUE TITLE
Defect in dtoolai-provenance(?)

### ISSUE THREAD

**Issue by tjelvar-olsson** [JIC-CSB/dtoolai#7]
Example code in here fails: https://dtoolai.readthedocs.io/en/latest/training.html#viewing-the-trained-model-metadata

With the error message below:

```
$ dtoolai-provenance example/mnistcnn/
Network architecture name: dtoolai.simpleScalingCNN
Model training parameters: {'batch_size': 128,
 'init_params': {'input_channels': 1, 'input_dim': 28},
 'input_channels': 1,
 'input_dim': 28,
 'learning_rate': 0.01,
 'loss_func': 'NLLLoss',
 'n_epochs': 1,
 'optimiser_name': 'SGD'}
Traceback (most recent call last):
  File "C:\Users\olssont\Anaconda3\envs\dtoolai-reverse-test\Scripts\dtoolai-provenance-script.py", line 10, in <module>
    sys.exit(print_provenance())
  File "C:\Users\olssont\Anaconda3\envs\dtoolai-reverse-test\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\olssont\Anaconda3\envs\dtoolai-reverse-test\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\olssont\Anaconda3\envs\dtoolai-reverse-test\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\olssont\Anaconda3\envs\dtoolai-reverse-test\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\olssont\Anaconda3\envs\dtoolai-reverse-test\lib\site-packages\dtoolai\utils.py", line 72, in print_provenance
    source_ds_uri = ttm.dataset.get_annotation("source_ds_uri")
  File "C:\Users\olssont\Anaconda3\envs\dtoolai-reverse-test\lib\site-packages\dtoolcore\__init__.py", line 518, in get_annotation
    raise(DtoolCoreKeyError())
dtoolcore.DtoolCoreKeyError
```

**Comment by mrmh2** [comment]
Fixed in fa7ca96797f54d156edeb685ad5cb98b958f97d1
